# =========================================================
#  ____  _               _ _
# |  _ \(_)             (_) |
# | |_) |_| ___  ___ ___  _| |_ ___
# |  _  | |/ __|/ __/ _ \| | __/ _ \
# | |_) | |\__ \ (__ (_) | | |_ (_) |
# |____/|_|____/\___\___/|_|\__\___/
# Biscoito config - Modulo: ANIMAÇÕES
# =========================================================

# ---------------- ANIMATIONS -------------
 animations {
    enabled = true

    bezier = myEase, 0.25, 0.1, 0.25, 1
    animation = windowsIn, 1, 5, default, slide
    animation = windowsOut, 1, 5, default, slide
}
