# =========================================================
#  ____  _               _ _
# |  _ \(_)             (_) |
# | |_) |_| ___  ___ ___  _| |_ ___
# |  _  | |/ __|/ __/ _ \| | __/ _ \
# | |_) | |\__ \ (__ (_) | | |_ (_) |
# |____/|_|____/\___\___/|_|\__\___/
# Biscoito config - Modulo: AUTOSTART (scripts ou app que iniciam junto do hypr)
# =========================================================

# ---------------- AUTOSTART ----------------
exec-once = waypaper --backend awww --restore
exec-once = swaync
#exec-once = ~/.config/swaync/spotify-notify.sh
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = /usr/bin/kwalletd5
exec-once = kwalletd6
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#exec-once = ~/.config/scripts/hyprbar.sh
#exec-once = dms run
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = libinput-gestures
exec-once = ~/.config/scripts/dormiu.sh
exec-once = ~/killRust.sh
exec-once = echo 0 > ~/.cache/faiz/count 
exec-once = ~/.config/hypr/scripts/faiz.sh
#exec-once = ~/.config/scripts/net.sh
exec-once = waybar
exec-once = mpv /home/bixcoitu/Músicas/mesaSom/faiz_end.wav
brave --password-store=basic

