# Hyprland with colors from Matugen
#
# You can use this template by adding the following to config.toml:
#
# [templates.hypr]
# input_path = "~/.config/matugen/templates/hyprland-colors.conf"
# output_path = "~/.config/hypr/colors.conf"
#
# and then on hyprland.conf:
# source = ~/.config/hypr/colors.conf

general {
    # Borda ativa
    $active_border = rgba(ec5748ee) rgba(e7bdb7ee) 45deg

    # Borda inativa
    $inactive_border = rgba(ffb4a9ee)
}
