# =========================================================
#  ____  _               _ _
# |  _ \(_)             (_) |
# | |_) |_| ___  ___ ___  _| |_ ___
# |  _  | |/ __|/ __/ _ \| | __/ _ \
# | |_) | |\__ \ (__ (_) | | |_ (_) |
# |____/|_|____/\___\___/|_|\__\___/
# Biscoito config - Modulo: CORES (via Matugen)
# =========================================================

# Hyprland with colors from Matugen
#
# You can use this template by adding the following to config.toml:
#
# [templates.hypr]
# input_path = "~/.config/matugen/templates/hyprland-colors.conf"
# output_path = "~/.config/hypr/colors.conf"
#
# and then on hyprland.conf:
# source = ~/.config/hypr/colors.conf

general {
    # Borda ativa
    $active_border = rgba(f54273ee) rgba(e5bdc1ee) 45deg

    # Borda inativa
    $inactive_border = rgba(ffb2beee)
}
