# =========================================================
#  ____  _               _ _
# |  _ \(_)             (_) |
# | |_) |_| ___  ___ ___  _| |_ ___
# |  _  | |/ __|/ __/ _ \| | __/ _ \
# | |_) | |\__ \ (__ (_) | | |_ (_) |
# |____/|_|____/\___\___/|_|\__\___/
# Biscoito config - Modulo: DECORAÇÃO
# =========================================================

# ---------------- DECORATION ----------------
general {
    gaps_in = 4
    gaps_out = 10
    border_size = 2
    layout = dwindle
    col.active_border = $active_border
    col.inactive_border = $inactive_border
}


decoration {
    rounding = 10
    blur {
        enabled = false
    }
    active_opacity = 1.0
    inactive_opacity = 0.88 
    fullscreen_opacity = 1.0
}
