# =========================================================
#  ____  _               _ _
# |  _ \(_)             (_) |
# | |_) |_| ___  ___ ___  _| |_ ___
# |  _  | |/ __|/ __/ _ \| | __/ _ \
# | |_) | |\__ \ (__ (_) | | |_ (_) |
# |____/|_|____/\___\___/|_|\__\___/
# Biscoito config - Modulo: TELA DE BLOQUEIO
# =========================================================

background {
    monitor =
    path = ~/.cache/lockscreen-wallpaper 
    blur_passes = 1
    blur_size = 2
}

label {
    monitor =
    text = cmd[update:5000] ~/.config/hypr/scripts/status.sh
    font_family = JetBrains Mono Nerd Font
    position = -30, -20
    halign = right
    valign = top
    font_size = 12
}

label {
    monitor =
    text = Whose eyes are those eyes?
    font_family = JetBrains Mono Nerd Font
    font_size = 12
    color = rgba(255,255,255,0.8)
    position = 20, -20
    halign = left
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    font_family = JetBrains Mono Nerd Font
    font_size = 80
    position = 0, 140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] LC_TIME=pt_BR.UTF-8 date '+%A, %d de %B de %Y' | sed 's/.*/\u&/'
    font_family = JetBrains Mono Nerd Font
    font_size = 20
    position = 0, 60
    halign = center
    valign = center
}


input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255,255,255,0.3)
    inner_color = rgba(0,0,0,0.5)
    font_color = rgba(255,255,255,1.0)
    fade_on_empty = false
    font_family = JetBrains Mono Nerd Font
    placeholder_text = <i> Digite a senha... </i>
}
