# =========================================================
#  ____  _               _ _
# |  _ \(_)             (_) |
# | |_) |_| ___  ___ ___  _| |_ ___
# |  _  | |/ __|/ __/ _ \| | __/ _ \
# | |_) | |\__ \ (__ (_) | | |_ (_) |
# |____/|_|____/\___\___/|_|\__\___/
# Biscoito config - Hyprland version - MAIN
# =========================================================

# ------------------- COLORS ----------------
source = ~/.config/hypr/colors.conf

# ---------------- VARIAVEIS ----------------
source = ~/.config/hypr/variables.conf

# ---------------- DECORATION ----------------
source = ~/.config/hypr/decoration.conf

# ---------------- INPUT ----------------
source = ~/.config/hypr/input.conf

# ---------------- AUTOSTART ----------------
source = ~/.config/hypr/autostart.conf

# ---------------- ATALHOS ----------------
source = ~/.config/hypr/bindings.conf

# ---------------- WINDOW RULES -----------
source = ~/.config/hypr/windowrules.conf

# ---------------- ANIMATIONS -------------
source = ~/.config/hypr/animations.conf
