background {
    monitor =
    path = /home/bixcoitu/.config/hypr/scripts/cute.jpg
    blur_passes = 1
    blur_size = 2
}

label {
    monitor =
    text = cmd[update:5000] ~/.config/hypr/scripts/status.sh
    font_family = JetBrains Mono Nerd Font
    position = -30, -20
    halign = right
    valign = top
    font_size = 12
}

label {
    monitor =
    text = Whose eyes are those eyes?
    font_family = JetBrains Mono Nerd Font
    font_size = 12
    color = rgba(255,255,255,0.8)
    position = 20, -20
    halign = left
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    font_family = JetBrains Mono Nerd Font
    font_size = 80
    position = 0, 140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] LC_TIME=pt_BR.UTF-8 date '+%A, %d de %B de %Y' | sed 's/.*/\u&/'
    font_family = JetBrains Mono Nerd Font
    font_size = 20
    position = 0, 60
    halign = center
    valign = center
}


input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255,255,255,0.3)
    inner_color = rgba(0,0,0,0.5)
    font_color = rgba(255,255,255,1.0)
    fade_on_empty = false
    font_family = JetBrains Mono Nerd Font
    placeholder_text = <i> Digite a senha... </i>
}

shape {
    size = 400, 130
    color = rgba(30, 30, 30, 0.85)

    rounding = 24

    position = 10, 10

    halign = left
    valign = bottom
}

image {
    path = /tmp/spotify-cover.jpg
    size = 85
    rounding = 10

    position = 25, 25

    halign = left
    valign = bottom
}

label {
    text = cmd[update:1000] playerctl -p spotify metadata title
    color = rgba(255, 255, 255, 1.0)

    font_size = 9
    font_family = JetBrains Mono Nerd Font

    position = 130, 95
    halign = left
    valign = bottom
}

label {
    text = cmd[update:1000] ~/.config/hypr/hyprlock/get_cover.sh
    color = rgba(255, 255, 255, 1.0)

    font_size = 9
    font_family = JetBrains Mono Nerd Font

    position = 130, 95
    halign = left
    valign = bottom
}

label {
    text = cmd[update:1000] playerctl -p spotify metadata artist
    color = rgba(180, 180, 180, 1.0)

    font_size = 8
    font_family = JetBrains Mono Nerd Font

    position = 130, 75
    halign = left
    valign = bottom
}

label {
    text = cmd[update:1000] ~/.config/hypr/hyprlock/progress_bar.sh

    color = rgba(255, 255, 255, 1.0)

    font_size = 9
    font_family = JetBrains Mono Nerd Font

    position = 130, 50

    halign = left
    valign = bottom
}
