# =========================================================
#  ____  _               _ _
# |  _ \(_)             (_) |
# | |_) |_| ___  ___ ___  _| |_ ___
# |  _  | |/ __|/ __/ _ \| | __/ _ \
# | |_) | |\__ \ (__ (_) | | |_ (_) |
# |____/|_|____/\___\___/|_|\__\___/
# Biscoito config - Modulo: VARIAVEIS
# =========================================================

# ------------------- MOD -------------------
#Define a tecla Super (aquela tecla com icone do Windows)
$mod = SUPER

# ---------------- VARIAVEIS ----------------
# Setas direcionais
$left = h
$down = j
$up = k
$right = l

# Terminal utilizado
$term = kitty

# Launcher de aplicativos com run e drun
$menu = rofi -show drun
$teste = hyprpicker

# Editor de código utilizado
$editor = kitty nvim

#Explorador de arquivos
$fm = dolphin

#Print
$screenshot = grim - | tee ~/Imagens/hyprland_prints/scrn-$(date +"%Y-%m-%d-%H-%M-%S").png | wl-copy
