# =========================================================
#  ____  _               _ _
# |  _ \(_)             (_) |
# | |_) |_| ___  ___ ___  _| |_ ___
# |  _  | |/ __|/ __/ _ \| | __/ _ \
# | |_) | |\__ \ (__ (_) | | |_ (_) |
# |____/|_|____/\___\___/|_|\__\___/
# Biscoito config - Modulo: WINDOWRULES (regras de janelas)
# =========================================================

#Regras de janelas (blur, opacidade, flutuante, tamanho, etc)
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(blueman-manager)$, center on
windowrule = match:class ^(blueman-manager)$, size 800 600
windowrule = match:class ^(blueman-manager)$, opacity 1

windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(nm-connection-editor)$, center on
windowrule = match:class ^(nm-connection-editor)$, size 800 600

windowrule = match:class ^(mpv)$, float on
windowrule = match:class ^(mpv)$, center on

windowrule = match:class ^(waypaper)$, float on
windowrule = match:class ^(waypaper)$, center on

windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(pavucontrol)$, center 800 600

windowrule = match:class ^(nwg-look)$, float on
windowrule = match:class ^(org.kde.ark)$, float on
windowrule = match:class ^(com.interversehq.qView)$, float on
windowrule = match:class ^(com.interversehq.qView)$, center on
windowrule = match:class ^(com.interversehq.qView)$, size 1080 620

windowrule = match:class ^(discord)$, opacity 1
windowrule = match:class ^(geany)$, opacity 0.90
windowrule = match:class ^(Spotify)$, opacity 0.87
windowrule = match:class ^(org.kde.dolphin)$, opacity 1
windowrule = match:class ^(file-png)$, float on
windowrule = match:class ^(file-jpeg)$, float on
windowrule = match:class ^(dolphin-emu)$, float on

windowrule = match:class ^(antigravity-ide)$, opacity 0.87

#Sim, essa sessão existe apenas pro gif da resenha... legal não acha?
windowrule = match:class ^(Gifview)$, opacity 0.88
windowrule = match:class ^(Gifview)$, center on
windowrule = match:class ^(Gifview)$, float on

windowrule = match:class ^(brave-lodlkdfmihgonocnmddehnfgiljnadcf-Default)$, opacity 1

windowrule = match:class ^(xdg-desktop-portal-gtk), float on
windowrule = match:class ^(xdg-desktop-portal-gtk), center on

windowrule = match:class ^(steam_app_0), float on
windowrule = match:class ^(steam_app_0), center on
windowrule = match:class ^(steam), center on
windowrule = match:class ^(explorer.exe), float on
windowrule = match:class ^(explorer.exe), center on
windowrule = match:class ^(discord), center on

#Isso faz determinados apps serem lançados em certos workspaces, ex: sempre que o discord iniciar
#ele vai pro workspace 5
windowrule = workspace 2, match:class ^(brave-browser)$

#Discord
windowrule = workspace 5, match:class ^(discord)$

#Code
windowrule = workspace 3, match:class ^(antigravity-ide)$
windowrule = workspace 3, match:class ^(antigravity)$
windowrule = workspace 3, match:class ^(org.kde.kate)$

#Dolphin
windowrule = workspace 8, match:class ^(org.kde.dolphin)$

#Spotify
windowrule = workspace 4, match:class ^(Spotify)$
#
#YouTube
windowrule = workspace 6, match:class ^(brave-agimnkijcaahngcdmfeangaknmldooml-Default)$
#Claude
windowrule = workspace 2, match:class ^(brave-fmpnliohjhemenmnlpbfagaolkdacoja-Default)$
#ChatGPT
windowrule = workspace 2, match:class ^(brave-cadlkienfkclaiaibeoongdcgmdikeeg-Default)$
#X (Twitter)
windowrule = workspace 7, match:class ^(brave-lodlkdfmihgonocnmddehnfgiljnadcf-Default)$
#Inst
windowrule = workspace 2, match:class ^(brave-akpamiohjfcnimfljfndmaldlcfphjmp-Default)$
#whpp
windowrule = workspace 10, match:class ^(brave-hnpfjngllnobngcgfapefoaidbinmjnm-Default)$
#Steam
windowrule = workspace 9, match:class ^(steam)$
windowrule = workspace 10, match:class ^(steam_app_0)$
windowrule = workspace 9, match:class ^(com.heroicgameslauncher.hgl)$

windowrule = workspace 11, match:title ^(.*ikachan.*)$
