# Hyprland with colors from Matugen
#
# You can use this template by adding the following to config.toml:
#
# [templates.hypr]
# input_path = "~/.config/matugen/templates/hyprland-colors.conf"
# output_path = "~/.config/hypr/colors.conf"
#
# and then on hyprland.conf:
# source = ~/.config/hypr/colors.conf

general {
    # Borda ativa
    $active_border = rgba({{colors.source_color.default.hex | replace: "#", ""}}ee) rgba({{colors.secondary.default.hex | replace: "#", ""}}ee) 45deg

    # Borda inativa
    $inactive_border = rgba({{colors.surface.default.hex | replace: "#", ""}}ee)
}
